package com.paytm.pojo;

public enum Outcome {
	REGISTRATION_SUCCESSFUL, 
	INVALID_LOGIN_CREDENTIALS, 
	USER_ALREADY_EXISTS, 
	INVALID_PASSWORD, 
	NEW_PASSWORD_AND_CONFIRM_PASSWORD_MISMATCH, 
	PASSWORD_CHANGE_SUCCESSFUL
}
