security:
  oauth2:
    client:
      client-id: trusted-app
      client-secret: secret
      access-token-uri: http://localhost:9999/uaa/oauth/token
      user-authorization-uri: http://localhost:9999/uaa/oauth/authorize
    resource:
      user-info-uri: http://localhost:9999/uaa/api/me

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    
server:
  context-path: /ui
  port: 8080
  
spring:
  social:
    twitter:
      appId: hUBIB6xTeiKPFCNozXzsSvi0r
      appSecret: 0tAnzTNTsqlY4Al3leRaXy6ESjQvq8nJWKz6lISXlEcRy1597t